# -*- coding: utf-8 -*-
"""EstruturasDeDecisaoPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kXZsZHcFW99Q0Ax4y-uJHAtRqZvOu6CY

1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
if (num1+num2 > 15):
  print("Soma maior que 15, resultado: " , num1+num2)

"""2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.
"""

num = int(input("Digite o número: "))
if(num<0):
  print("negativo")
elif(num==0):
  print("neutro")
else:
  print("positivo")

"""3. Leia a idade e informe se a pessoa é maior ou menor de idade

"""

age =int(input("Digite a idade: "))
if(age>=18):
  print("Maior de idade")
else:
  print("menor de idade")

"""4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

"""

temp=int(input("Digite a temperatuda: "))
if(temp<=15):
  print("frio")
elif (temp> 15 and temp<23):
  print("agradável")
else:
  print("quente")

"""5. Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

num1=int(input("Digite o primeiro número: "))
num2=int(input("Digite o segundo número: "))
if(num1==num2):
  print("números iguais")
else:
  print("números diferentes")

"""6. Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
*   ACESSO PERMITIDO caso a senha seja válida.
*   ACESSO NEGADO caso a senha seja inválida.

"""

senha=int(input("Digite a senha: "))
if(senha == 1234):
 print("ACESSO PERMITIDO")
else:
  print("ACESSO NEGADO")

"""7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.
"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
media = (nota1+nota2)/2
print(f"Média do aluno é {media:.2f}")
if(media <5):
  print("Aluno reprovado")
elif (media >= 5 and media <7):
  print("Aluno de exame")
else:
  print("Aluno aprovado")

"""8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.
"""

time1 = float(input("Digite a quantidade de gols do primeiro time: "))
time2 = float(input("Digite a quantidade de gols do segundo time: "))
if(time1>time2):
  print("Vitória do time 1!")
elif(time1==time2):
  print("Jogo empatado!")
else:
  print("Vitória do time 2!")

"""9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.

"""

turno = str(input("Informe qual turno você estuda: M para matutino, V para vespertino ou N para noturno"))
if (turno == "M"):
  print("Bom dia!")
elif(turno =="V"):
  print("Boa tarde")
elif(turno == "N"):
  print("Boa noite!")
else:
  print("Valor Invalido!")

"""10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
* Criança para 0 até 11 anos;
* Adolescente para 12 até 18 anos;
* Jovem para 19 até 24 anos;
* Adulto para 25 até 40 anos;
* Meia Idade para 41 até 60 anos;
* Idoso acima de 60 anos.

"""

idade = int(input("Informe a idade: "))
if (idade > 60):
  print("Idoso")
elif (idade >= 41):
  print("Meia idade")
elif (idade >=25):
  print("Adulto")
elif(idade >= 19):
  print("Jovem")
elif(idade >= 12):
  print("Adolescente")
else:
  print("Criança")

"""11. As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
*  salários até R 280,00 (incluindo) - aumento de 20 porc.
*  salários entre R 280,00 e R 700,00 - aumento de 15 porc.
*  salários entre R 700,00 e R 1500,00 - aumento de 10 porc.
*  salários de R 1500,00 em diante -  aumento de 5 porc.
Após o aumento ser realizado, informe na tela:
* o salário antes do reajuste;
* o percentual de aumento aplicado;
* o valor do aumento;
* o novo salário, após o aumento
"""

salar_atual = float(input("Informe o salário atual: "))
if ( salar_atual > 1500,00):
  sal_cor= salar_atual+(salar_atual*0.20); reaj= "5%"
elif (salar_atual > 700):
   sal_cor= salar_atual+(salar_atual*0.10); reaj= "10%"
elif (salar_atual > 280):
   sal_cor= salar_atual+(salar_atual*0.15); reaj= "15%"
else:
  sal_cor= salar_atual+(salar_atual*0.20); reaj= "20%"
print(f"O salário antes do reajuste era de: R$ {salar_atual:.2f}")
print(f"O ajuste aplicado foi de: {reaj}")
print(f"O valor de aumento foi de : R$ {sal_cor - salar_atual:.2f}")
print(f"O novo salário, após o aumento foi de: R$ {sal_cor:.2f}")

"""12. Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

"""

dia = int(input("Informe o número da semana: "))
if(dia ==1):
  print("Domingo")
elif(dia ==2):
  print("Segunda")
elif(dia ==3):
  print("terça")
elif(dia ==4):
  print("Quarta")
elif(dia ==5):
  print("Quinta")
elif(dia ==6):
  print("Sexta")
elif(dia ==7):
  print("Sábado")
else:
  print("Inválido")

"""13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de
Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
do usuário, faça a devida conversão.


"""

tipo = str(input("Escolha CF para converter Celcius para Fahrenheit ou FC para converter Fahrenheit para Celcius "))

if (tipo == "CF"):
  temp_cel= float(input("Digite a temperatura em Celcius: "))
  f= (temp_cel * 1.8) + 32
  print(f"{temp_cel}ºC são {f:.2f}ºF ")
elif(tipo == "FC"):
  temp_far = float(input("Digite a temperatura em  Fahrenheits : "))
  c= (temp_far - 32) * (5/9)
  print(f"{temp_far}ºF são {c:.2f}ºFC ")
else:
  print("Opção inválida, tente novamente")

"""14. Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
* Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
* Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
* Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
* Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

"""

idade = int(input("Informe a idade: "))
if (idade >= 65):
  print("Optativo")
elif (idade >= 18):
  print("Obrigatório")
elif (idade >=16):
  print("Optativo")
else:
  print("Proibido")

"""15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
* “Telefonou para a vítima? “
* “Esteve no local do crime?”
* “Mora perto da vítima? “
* “Devia para a vítima? “
* “Já trabalhou com a vítima? “
16. O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
Caso contrário, ele será classificado como “Inocente“.

"""

score = 0
resp1 = str(input("Telefonou para a vítima? s/n: ")).lower()
if (resp1 == "s"):
  score +=1
resp2 = str(input("Esteve no local do crime? s/n: ")).lower()
if (resp2 == "s"):
  score +=1
resp3 = str(input("Esteve no local do crime? s/n: ")).lower()
if (resp3 == "s"):
  score +=1
resp4 = str(input("Devia para a vítima? s/n: ")).lower()
if (resp3 == "s"):
  score +=1
resp5 = str(input("Já trabalhou com a vítima? s/n: ")).lower()
if (resp5 == "s"):
  score +=1

if(score == 5):
  print("Assassino")
elif( score >3):
  print("Cumplice")
elif(score >2):
  print("Suspeito")
else:
  print("Inocente")

"""17. Faça um programa que pergunte o preço de três produtos e informe qual produto
você deve comprar, sabendo que a decisão é sempre pelo mais barato.
"""

low_price = float(input("Informe o preço do primeiro produto: "))
sec = float(input("Informe o preço do segundo produto: "))
if(low_price > sec):
  low_price = sec
terc = float(input("Informe o preço do terceiro produto: "))
if (low_price > terc):
  low_price = terc
print(f"O menor preço é: {low_price} ")